version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      semantic-release:
        patterns:
          - "@semantic-release/*"
          - "semantic-release"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
