name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      issues: write
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
          cache: yarn

      - run: |
          yarn install --immutable
          yarn run test
          yarn run build
          yarn run lint
      - env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: yarn semantic-release
